/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CreationsRouteImport } from './routes/creations'
import { Route as FlowRouteImport } from './routes/flow'
import { Route as FutureRouteImport } from './routes/future'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as CreateAdjustRouteImport } from './routes/create/adjust'
import { Route as CreateBaseRouteImport } from './routes/create/base'
import { Route as CreateIngredientsRouteImport } from './routes/create/ingredients'
import { Route as CreateRecipeRouteImport } from './routes/create/recipe'
import { Route as CreateResultRouteImport } from './routes/create/result'
import { Route as CreateTasteRouteImport } from './routes/create/taste'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationsRoute = CreationsRouteImport.update({
  id: '/creations',
  path: '/creations',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowRoute = FlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureRoute = FutureRouteImport.update({
  id: '/future',
  path: '/future',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAdjustRoute = CreateAdjustRouteImport.update({
  id: '/create/adjust',
  path: '/create/adjust',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateBaseRoute = CreateBaseRouteImport.update({
  id: '/create/base',
  path: '/create/base',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIngredientsRoute = CreateIngredientsRouteImport.update({
  id: '/create/ingredients',
  path: '/create/ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRecipeRoute = CreateRecipeRouteImport.update({
  id: '/create/recipe',
  path: '/create/recipe',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateResultRoute = CreateResultRouteImport.update({
  id: '/create/result',
  path: '/create/result',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTasteRoute = CreateTasteRouteImport.update({
  id: '/create/taste',
  path: '/create/taste',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/creations': typeof CreationsRoute
  '/flow': typeof FlowRoute
  '/future': typeof FutureRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/technology': typeof TechnologyRoute
  '/vision': typeof VisionRoute
  '/create/adjust': typeof CreateAdjustRoute
  '/create/base': typeof CreateBaseRoute
  '/create/ingredients': typeof CreateIngredientsRoute
  '/create/recipe': typeof CreateRecipeRoute
  '/create/result': typeof CreateResultRoute
  '/create/taste': typeof CreateTasteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/creations': typeof CreationsRoute
  '/flow': typeof FlowRoute
  '/future': typeof FutureRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/technology': typeof TechnologyRoute
  '/vision': typeof VisionRoute
  '/create/adjust': typeof CreateAdjustRoute
  '/create/base': typeof CreateBaseRoute
  '/create/ingredients': typeof CreateIngredientsRoute
  '/create/recipe': typeof CreateRecipeRoute
  '/create/result': typeof CreateResultRoute
  '/create/taste': typeof CreateTasteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/creations': typeof CreationsRoute
  '/flow': typeof FlowRoute
  '/future': typeof FutureRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/technology': typeof TechnologyRoute
  '/vision': typeof VisionRoute
  '/create/adjust': typeof CreateAdjustRoute
  '/create/base': typeof CreateBaseRoute
  '/create/ingredients': typeof CreateIngredientsRoute
  '/create/recipe': typeof CreateRecipeRoute
  '/create/result': typeof CreateResultRoute
  '/create/taste': typeof CreateTasteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/community'
    | '/creations'
    | '/flow'
    | '/future'
    | '/home'
    | '/profile'
    | '/register'
    | '/technology'
    | '/vision'
    | '/create/adjust'
    | '/create/base'
    | '/create/ingredients'
    | '/create/recipe'
    | '/create/result'
    | '/create/taste'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/community'
    | '/creations'
    | '/flow'
    | '/future'
    | '/home'
    | '/profile'
    | '/register'
    | '/technology'
    | '/vision'
    | '/create/adjust'
    | '/create/base'
    | '/create/ingredients'
    | '/create/recipe'
    | '/create/result'
    | '/create/taste'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/community'
    | '/creations'
    | '/flow'
    | '/future'
    | '/home'
    | '/profile'
    | '/register'
    | '/technology'
    | '/vision'
    | '/create/adjust'
    | '/create/base'
    | '/create/ingredients'
    | '/create/recipe'
    | '/create/result'
    | '/create/taste'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  CommunityRoute: typeof CommunityRoute
  CreationsRoute: typeof CreationsRoute
  FlowRoute: typeof FlowRoute
  FutureRoute: typeof FutureRoute
  HomeRoute: typeof HomeRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  TechnologyRoute: typeof TechnologyRoute
  VisionRoute: typeof VisionRoute
  CreateAdjustRoute: typeof CreateAdjustRoute
  CreateBaseRoute: typeof CreateBaseRoute
  CreateIngredientsRoute: typeof CreateIngredientsRoute
  CreateRecipeRoute: typeof CreateRecipeRoute
  CreateResultRoute: typeof CreateResultRoute
  CreateTasteRoute: typeof CreateTasteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creations': {
      id: '/creations'
      path: '/creations'
      fullPath: '/creations'
      preLoaderRoute: typeof CreationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future': {
      id: '/future'
      path: '/future'
      fullPath: '/future'
      preLoaderRoute: typeof FutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/adjust': {
      id: '/create/adjust'
      path: '/create/adjust'
      fullPath: '/create/adjust'
      preLoaderRoute: typeof CreateAdjustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/base': {
      id: '/create/base'
      path: '/create/base'
      fullPath: '/create/base'
      preLoaderRoute: typeof CreateBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/ingredients': {
      id: '/create/ingredients'
      path: '/create/ingredients'
      fullPath: '/create/ingredients'
      preLoaderRoute: typeof CreateIngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/recipe': {
      id: '/create/recipe'
      path: '/create/recipe'
      fullPath: '/create/recipe'
      preLoaderRoute: typeof CreateRecipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/result': {
      id: '/create/result'
      path: '/create/result'
      fullPath: '/create/result'
      preLoaderRoute: typeof CreateResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/taste': {
      id: '/create/taste'
      path: '/create/taste'
      fullPath: '/create/taste'
      preLoaderRoute: typeof CreateTasteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  CommunityRoute: CommunityRoute,
  CreationsRoute: CreationsRoute,
  FlowRoute: FlowRoute,
  FutureRoute: FutureRoute,
  HomeRoute: HomeRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  TechnologyRoute: TechnologyRoute,
  VisionRoute: VisionRoute,
  CreateAdjustRoute: CreateAdjustRoute,
  CreateBaseRoute: CreateBaseRoute,
  CreateIngredientsRoute: CreateIngredientsRoute,
  CreateRecipeRoute: CreateRecipeRoute,
  CreateResultRoute: CreateResultRoute,
  CreateTasteRoute: CreateTasteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
